### PR TITLE
add colour and name output to what is running concurrently

### LINKED ISSUE #84: ❤️ add colour and name output to what is running concurrently

### PR DESCRIPTION
**Pull request by chrillep**
makes it easier to se what is doing what :)

closes #84 

```shell
prefixColors: a list of colors as supported by [chalk](https://www.npmjs.com/package/chalk) or auto for an automatically picked color. If concurrently would run more commands than there are colors, the last color is repeated, unless if the last color value is auto which means following colors are automatically picked to vary. Prefix colors specified per-command take precedence over this list.

 - Custom names and colored prefixes

     $ concurrently --names "HTTP,WATCH" -c "bgBlue.bold,bgMagenta.bold"
     "http-server" "npm run watch"

 - Auto varying colored prefixes

     $ concurrently -c "auto" "npm run watch" "http-server"

 - Mixing auto and manual colored prefixes

     $ concurrently -c "red,auto" "npm run watch" "http-server" "echo hello"

```

ref:
* https://github.com/open-cli-tools/concurrently

### CODE REVIEW

**Comment by mrtimbrook** [comment]
I like it! It looks like this removes the `$STORYBOOK_PORT` option. Other than that it looks good so if you can add that back in I'll go ahead and merge

**Comment by chrillep** [comment]
whoops ill add it back. good eye! :)

**Comment by chrillep** [comment]
$STORYBOOK_PORT fixed :)

**Comment by chrillep** [comment]
@mrtimbrook ping

**Comment by mrtimbrook** [comment]
Thanks for this and sorry for the delayed response!

**Pull request merged**
