### PR TITLE
Updated/fixed various things

### PR DESCRIPTION
**Pull request by f4bio**
- Updated all kinds of deps
- fixed various linting errors
- fixed vulnerable npm package
- add php8.2 support

### CODE REVIEW

**Comment by mrtimbrook** [comment]
Thanks for this. 

I'm getting an error when launching blast on an existing project:

```
Error: Cannot find module '@storybook/source-loader'
[storybook] Require stack:
[storybook] - ./node_modules/@storybook/addon-storysource/dist/preset.js
[storybook] - ./node_modules/@storybook/core-common/dist/index.js
[storybook] - ./node_modules/@storybook/telemetry/dist/index.js
[storybook] - ./node_modules/@storybook/cli/dist/generate.js
[storybook] - ./node_modules/@storybook/cli/bin/index.js
[storybook] - ./node_modules/storybook/index.js
[storybook]     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
[storybook]     at Function.resolve (node:internal/modules/cjs/helpers:116:19)
[storybook]     at Object.webpack (./node_modules/@storybook/addon-storysource/dist/preset.js:3:550)
[storybook]     at ./node_modules/@storybook/core-common/dist/index.js:15:1184
[storybook]     at async starter (./node_modules/@storybook/builder-webpack5/dist/index.js:1:7688)
[storybook]     at async Module.start (./node_modules/@storybook/builder-webpack5/dist/index.js:1:11672)
[storybook]     at async storybookDevServer (./node_modules/@storybook/core-server/dist/index.js:66:2459)
[storybook]     at async buildOrThrow (./node_modules/@storybook/core-server/dist/index.js:60:8290)
[storybook]     at async buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:120:1397)
[storybook]     at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:65:3948)
```

**Comment by f4bio** [comment]
> I'm getting an error when launching blast on an existing project:
> ...

I'm not at my desktop currently, but I fired up a codespace for some debugging. 

- `npm ls @storybook/source-loader` seems to be empty
- `@storybook/source-loader` seems to be referenced couple of times in [storybook's repo](https://github.com/search?q=repo%3Astorybookjs%2Fstorybook+%40storybook%2Fsource-loader+language%3AJSON&type=code) as dependency (and otherwise)

so maybe `@storybook/source-loader` just has to be added to `dependencies`?!

I'll investigate some more and keep you posted ;)

btw: to reproduce this, just initialize a new laravel project (`composer create-project laravel/laravel example-app`) and add blast (`composer require area17/blast`)?

**Comment by mrtimbrook** [comment]
Thanks!

> btw: to reproduce this, just initialize a new laravel project (composer create-project laravel/laravel example-app) and add blast (composer require area17/blast)?

You may need to create a story too. Running `php artisan blast:demo` should be a quick way to get one up and running. If everything is working correctly there'll be a 'Source' tab alongside the controls and a11y tabs.

**Comment by f4bio** [comment]
apparently, thats not the only thing which broke during my `storybook@7.6` upgrade...  
I'll go through the [MIGRATION](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)-guide again asap. 

Since I'm not even having an approximate ETA, I'm going to close this PR (and create a new one eventually).

Sorry for any inconvenience!

**Comment by mrtimbrook** [comment]
No problem. Thanks for all of your work on this. I've also been looking into upgrading to 7.6 and while nothing looks to break it looks like it's throwing a lot of warnings from within some of the Storybook dependencies. Is that what you were seeing?

One other thing I noticed, you had updated the lint-staged package to 15 which drops support for Node 16. I know that Node 16 is end of life but I'd prefer if we could keep the Node 16 support until it is officially dropped by storybook in 8.0.

**Pull request closed without merging**
